require: rubocop-rails
AllCops:
  SuggestExtensions: false
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**
    - config/**
    - bin/**
  NewCops: enable
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Metrics/MethodLength:
  Max: 20
